[tool.black]
line-length = 125
skip-string-normalization = true

[tool.isort]
profile = "black"
combine_as_imports = true
combine_star = true
line_length = 125

[tool.pyright]
reportUnnecessaryTypeIgnoreComment = "warning"
pythonVersion = "3.13"
typeCheckingMode = "basic"
strictParameterNoneValue = false
include = [
    "main/cogs",
    "main/cogs/utils"
]
exclude = [
    "**/__pycache__",
    "build",
    "dist"
]